"use strict";
let myName = 'Sunny';
console.log(myName == '$unny');
console.log(myName != '$unny');
console.log(myName[0].toUpperCase() === myName[0]);
console.log(myName[0].toLowerCase() === myName[0]);
console.log(5 < 4);
console.log(5 != 5);
console.log(10 > 8);
console.log(100 < 80);
console.log(9 >= 9);
let a = 10;
let b = 7;
console.log(a == 10 && b > 5);
console.log(a == 10 || b < 5);
let items = ['banana', 'orange', 'apple', 'grapes'];
console.log(items[0] == 'banana');
console.log(items[0] == 'Banana');
